### ISSUE TITLE
"Cannot accept session because it is not pending or does not exist" error

### ISSUE THREAD

**Issue by samueljun** [MyPureCloud/purecloud-webrtc-sdk#12]
Hi,

I'm seeing a high number of "Cannot accept session because it is not pending or does not exist" from the "on-error" event. Can you describe why this error would be thrown? I think this might be part of the reason why agents are reporting that they go into a "Not Responding" state frequently.

Thanks,
Sam

**Comment by xdumaine** [comment]
@samueljun I'm investigating, but something to look into on your side. Can you confirm with logging that the session is received prior to receiving that error? Generally, the common case for that error is attempting to accept the session after it has been canceled by the system for not receiving a response before the queue timeout. The default queue timeout is 8 seconds, so if agents don't answer prior to that, the SDK will receive a cancel/retract for the session, which will trigger the event  `cancelPendingSession`

`sdk.on('cancelPendingSession', (id) => {})`

**Comment by samueljun** [comment]
Yes they are using persistent connection.

Our code for accepting the "pendingSession" is super simple since we wanted to have auto-accept for all our agents. We accept as soon as the "pendingSession" event is received in the client code. 

```js
    sdk.on("pendingSession", ({ id, address, conversationId, autoAnswer }) => {
      sdk.acceptPendingSession(id);
    });
```

We'll log to see if we received the session prior to receiving the error. We're currently trying to see if increasing the queue timeout will alleviate the issue.

**Comment by xdumaine** [comment]
@samueljun do you have any other code that tries to call `acceptPendingSession`? For persistent connection, you won't receive a new `pendingSession` on each new call, since there's only the initial one. It's possible you've got a notifications channel set up, and when the new conversation alerts, you're calling `acceptPendingSession` on the webrtc sdk, which doesn't have the context.

To answer calls while on an active persistent connection, you'd want to `PATCH` the agent's participant on the conversation `{ state: 'CONNECTED' }`. This is a little confusing because when you're using persistent connection, it breaks the 1:1 association of webrtc connection to conversation. 

We might be able to wrap this up in the webrtc sdk, but it'd still require that you have a notifications channel set up, since managing that channel is currently out of scope for this SDK. Let me know what you think about how difficult that'd be for you to do, and we can maybe work to add it here.

**Comment by samueljun** [comment]
No, that code snippet is the only spot in the repo that uses `acceptPendingSession`.

And yes to account for the active persistent connection, we are currently sending the `PATCH { state: 'CONNECTED' }` for the agent's participant as soon at the Conversation comes in. We send this as soon as the Conversation is sent to the agent over the WebSocket notification, and the agent is "alerting". 

Not sure if this is a problem, but this `PATCH` request is also sent for the first time setup as well. Meaning that for the first call the agent receives after setup, we trigger `sdk.acceptPendingSession` as well as the `PATCH`.

**Comment by samueljun** [comment]
PS: I would recommend adding the info about the persistent connection in the [WebRTC SDK documentation](https://developer.mypurecloud.com/api/webrtcsdk/) since it wasn't immediately clear.

**Comment by samueljun** [comment]
We are currently defaulting our Alerting Timeouts to 20 seconds for most of our queues, which should be plenty of time for the "pendingSession" event to make it to the agent's browser and for the `acceptPendingSession` request make it to PureCloud.

**Comment by samueljun** [comment]
What happens behind the scenes for the WebRTC SDK client to become the effective station for the agent? Is there a way to detect that the WebRTC SDK client is not the effective station for the agent?

**Comment by xdumaine** [comment]
> I would recommend adding the info about the persistent connection in the WebRTC SDK documentation since it wasn't immediately clear.

Definitely. I'll work on that soon.

> We are currently defaulting our Alerting Timeouts to 20 Seconds

I agree. This should be plenty of time.

> What happens behind the scenes for the WebRTC SDK client to become the effective station for the agent?

The station association itself is not part of the SDK; it is really only a passive station like having a physical phone plugged in. In order to associate with that station, you'd `PUT` to `/api/v2/users/{userId}/station/associatedstation/{stationId}`

> Is there a way to detect that the WebRTC SDK client is not the effective station for the agent?

Yes. A `GET` to `api/v2/users/{userId}/station` will return the current station information. A WebRTC station is indicated by the `type` which will have a (static; this is part of our internal station metabase configuration) value of `inin_webrtc_softphone`

**Comment by xdumaine** [comment]
> And yes to account for the active persistent connection, we are currently sending the PATCH { state: 'CONNECTED' } for the agent's participant as soon at the Conversation comes in. 

> Not sure if this is a problem, but this PATCH request is also sent for the first time setup as well. 

That is not a problem; it sounds like you're doing the right thing. I'm investigating on the service some possible latent delivery of the session invitations. For comparison, could you share your numbers from the original problem (high numbers of that error, and agents going not responding). If you'd rather not post them publicly, feel free to contact me directly at xander.dumaine@genesys.com

**Comment by xdumaine** [comment]
I believe we tracked this down to both the SDK and the consuming code calling `acceptPendingSession` on the same session.
