### ISSUE TITLE
Provided options to acceptPendingSession are ignored

### ISSUE THREAD

**Issue by xdumaine** [MyPureCloud/purecloud-webrtc-sdk#7]
The optional options object documented for this method is actually not wired up in the code, so providing an existing mediaStream or audioElement is not working.

**Comment by emilyeisenberg-cricket** [comment]
I recently started using this library to hook up PureCloud to my company's website and ran into this issue where the `mediaStream` and `audioElement` properties weren't hooked up. We need these things for our integration. Is there any plan for this to be fixed?

If not, would you accept pull requests to fix it? I'm currently building off of the 1.2.0 branch though, because I couldn't get the new version in master to work.

**Comment by xdumaine** [comment]
@emilyeisenberg-cricket I can enable 2.0.0 for your org (there was a backend delay in enabling a piece of functionality required for it, but it's in Limited release now). We would gladly accept PRs to fix those if you are willing to contribute them, otherwise, I can try to get those triaged up to get fixed sooner (ideally in the 2.0.0). Please send me an email at xander.dumaine@genesys.com with your organization ID and I'll get 2.0.0 enabled for you (1.2.0 will still work).
